<#
.SYNOPSIS
    Deploy Indoor Navigation Azure infrastructure.

.DESCRIPTION
    Logs in to Azure (if needed), creates the subscription-level deployment,
    and outputs resource endpoints for local .env configuration.

.PARAMETER Environment
    Target environment: dev, staging, or prod. Default: dev

.PARAMETER SkipLogin
    Skip az login if you're already authenticated.
#>
param(
    [ValidateSet('dev', 'staging', 'prod')]
    [string]$Environment = 'dev',

    [switch]$SkipLogin
)

$ErrorActionPreference = 'Stop'
$SubscriptionId = '2f284205-cfd3-4df8-8a90-b198c9e0721e'

Write-Host "`n=== Indoor Navigation Infrastructure Deployment ===" -ForegroundColor Cyan
Write-Host "Environment : $Environment"
Write-Host "Subscription: $SubscriptionId"
Write-Host "Region      : swedencentral`n"

# --- Authentication ---
if (-not $SkipLogin) {
    Write-Host "Logging in to Azure (device code flow)..." -ForegroundColor Yellow
    az login --use-device-code --output none
}

az account set --subscription $SubscriptionId
Write-Host "Active subscription: $(az account show --query name -o tsv)" -ForegroundColor Green

# --- Deploy ---
$templateFile = Join-Path $PSScriptRoot 'infra\main.bicep'
$paramsFile   = Join-Path $PSScriptRoot "infra\parameters.$Environment.json"
$deploymentName = "indoornav-$Environment-$(Get-Date -Format 'yyyyMMdd-HHmmss')"

Write-Host "`nStarting deployment: $deploymentName" -ForegroundColor Yellow
Write-Host "Template : $templateFile"
Write-Host "Parameters: $paramsFile`n"

$result = az deployment sub create `
    --name $deploymentName `
    --location swedencentral `
    --template-file $templateFile `
    --parameters $paramsFile `
    --output json | ConvertFrom-Json

if ($LASTEXITCODE -ne 0) {
    Write-Host "Deployment FAILED." -ForegroundColor Red
    exit 1
}

Write-Host "`nDeployment succeeded!" -ForegroundColor Green

# --- Output endpoints ---
$outputs = $result.properties.outputs

Write-Host "`n=== Resource Endpoints ===" -ForegroundColor Cyan
Write-Host "API URL           : $($outputs.apiUrl.value)"
Write-Host "Functions URL     : $($outputs.functionsUrl.value)"
Write-Host "Blob Endpoint     : $($outputs.blobEndpoint.value)"
Write-Host "Cosmos Endpoint   : $($outputs.cosmosEndpoint.value)"
Write-Host "Gremlin Endpoint  : $($outputs.gremlinEndpoint.value)"
Write-Host "Vision Endpoint   : $($outputs.visionEndpoint.value)"
Write-Host "OpenAI Endpoint   : $($outputs.openaiEndpoint.value)"
Write-Host "Search Endpoint   : $($outputs.searchEndpoint.value)"
Write-Host "SignalR Host      : $($outputs.signalrHostName.value)"

# --- Generate .env file for backend ---
$envContent = @"
# Auto-generated by deploy.ps1 — $((Get-Date).ToString('yyyy-MM-dd HH:mm:ss'))
AZURE_STORAGE_BLOB_ENDPOINT=$($outputs.blobEndpoint.value)
AZURE_COSMOS_ENDPOINT=$($outputs.cosmosEndpoint.value)
AZURE_COSMOS_GREMLIN_ENDPOINT=$($outputs.gremlinEndpoint.value)
AZURE_VISION_ENDPOINT=$($outputs.visionEndpoint.value)
AZURE_OPENAI_ENDPOINT=$($outputs.openaiEndpoint.value)
AZURE_OPENAI_GPT_DEPLOYMENT=$($outputs.gptDeployment.value)
AZURE_OPENAI_EMBEDDING_DEPLOYMENT=$($outputs.embeddingDeployment.value)
AZURE_SEARCH_ENDPOINT=$($outputs.searchEndpoint.value)
AZURE_SIGNALR_HOSTNAME=$($outputs.signalrHostName.value)
APPLICATIONINSIGHTS_CONNECTION_STRING=$($outputs.appInsightsConnectionString.value)
"@

$envPath = Join-Path $PSScriptRoot 'backend\.env'
$envContent | Out-File -FilePath $envPath -Encoding utf8 -Force
Write-Host "`n.env written to: $envPath" -ForegroundColor Green

Write-Host "`nNext steps:" -ForegroundColor Yellow
Write-Host "  1. cd backend && pip install -r requirements.txt"
Write-Host "  2. uvicorn app.main:app --reload"
Write-Host ""
