// This file is auto-generated by setup-auth.ps1
// Replace placeholder values after running the registration script.

export const msalConfig = {
  auth: {
    clientId: "1d2e6a91-befd-48f5-9d2b-1cf49d4a95a8",
    authority: "https://login.microsoftonline.com/4db5932d-880c-433a-aff2-16123280ad60",
    redirectUri: window.location.origin,
  },
  cache: {
    cacheLocation: "sessionStorage",
    storeAuthStateInCookie: false,
  },
};

export const apiScope = "api://68ffc283-39c3-4e25-8186-3e83e891d1d6/access_as_user";